import type { Metadata } from "next";
import { Geist, Geist_Mono , Amiri } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/Providers/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "@/components/theme-provider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const amiri = Amiri({
  variable: "--font-amiri", 
  weight: ['400', '700'],  // adjust weights as needed
  subsets: ['arabic'],     // you can add 'arabic' if required
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${amiri.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
       
        <AuthProvider>
        {children}
        <Toaster />
        </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
